name: SamJoyKaur
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8898999036755413
title: Hello This Is Sam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070709'
    - '#be3191'
    - '#fefefc'
    - '#c5ae68'
    - '#4aa524'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.2275731402914971
  rhythmicContrast: 0.75
purpose: []
